import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

df = pd.read_csv('user_social_clustered.csv', sep = '\t', index_col=0)

print(df.head())
# Cluster 0 plot
fig, axes = plt.subplots(nrows=2, ncols=1)
df.loc[df[' cluster']==0,' about'].value_counts().plot(kind='bar', ax=axes[0])
axes[0].set_ylabel('about')
df.loc[df[' cluster']==0,' country'].value_counts().plot(kind='bar', ax=axes[1])
axes[1].set_ylabel('country')
plt.suptitle('Cluster 0')
fig, axes = plt.subplots(nrows=2, ncols=1)
df.loc[df[' cluster']==0,' city'].value_counts().plot(kind='bar', ax=axes[0])
axes[0].set_ylabel('city')
df.loc[df[' cluster']==0,' category'].value_counts().plot(kind='bar', ax=axes[1])
axes[1].set_ylabel('category')
plt.suptitle('Cluster 0')
fig, axes = plt.subplots(nrows=1, ncols=1)
df.loc[df[' cluster']==0,' description'].value_counts().plot(kind='bar', ax=axes)
axes.set_ylabel('description')
plt.suptitle('Cluster 0')
plt.show()
plt.close()
# Cluster 1 plot
fig, axes = plt.subplots(nrows=2, ncols=1)
df.loc[df[' cluster']==1,' about'].value_counts().plot(kind='bar', ax=axes[0])
axes[0].set_ylabel('about')
df.loc[df[' cluster']==1,' country'].value_counts().plot(kind='bar', ax=axes[1])
axes[1].set_ylabel('country')
plt.suptitle('Cluster 1')
fig, axes = plt.subplots(nrows=2, ncols=1)
df.loc[df[' cluster']==1,' city'].value_counts().plot(kind='bar', ax=axes[0])
axes[0].set_ylabel('city')
df.loc[df[' cluster']==1,' category'].value_counts().plot(kind='bar', ax=axes[1])
axes[1].set_ylabel('category')
plt.suptitle('Cluster 1')
fig, axes = plt.subplots(nrows=1, ncols=1)
df.loc[df[' cluster']==1,' description'].value_counts().plot(kind='bar', ax=axes)
axes.set_ylabel('description')
plt.suptitle('Cluster 1')
plt.show()
plt.close()
# Cluster 2 plot
fig, axes = plt.subplots(nrows=2, ncols=1)
df.loc[df[' cluster']==2,' about'].value_counts().plot(kind='bar', ax=axes[0])
axes[0].set_ylabel('about')
df.loc[df[' cluster']==2,' country'].value_counts().plot(kind='bar', ax=axes[1])
axes[1].set_ylabel('country')
plt.suptitle('Cluster 2')
fig, axes = plt.subplots(nrows=2, ncols=1)
df.loc[df[' cluster']==2,' city'].value_counts().plot(kind='bar', ax=axes[0])
axes[0].set_ylabel('city')
df.loc[df[' cluster']==2,' category'].value_counts().plot(kind='bar', ax=axes[1])
axes[1].set_ylabel('category')
plt.suptitle('Cluster 2')
fig, axes = plt.subplots(nrows=1, ncols=1)
df.loc[df[' cluster']==2,' description'].value_counts().plot(kind='bar', ax=axes)
axes.set_ylabel('description')
plt.suptitle('Cluster 2')
plt.show()
plt.close()
# Cluster 3 plot
fig, axes = plt.subplots(nrows=2, ncols=1)
df.loc[df[' cluster']==3,' about'].value_counts().plot(kind='bar', ax=axes[0])
axes[0].set_ylabel('about')
df.loc[df[' cluster']==3,' country'].value_counts().plot(kind='bar', ax=axes[1])
axes[1].set_ylabel('country')
plt.suptitle('Cluster 3')
fig, axes = plt.subplots(nrows=2, ncols=1)
df.loc[df[' cluster']==3,' city'].value_counts().plot(kind='bar', ax=axes[0])
axes[0].set_ylabel('city')
df.loc[df[' cluster']==3,' category'].value_counts().plot(kind='bar', ax=axes[1])
axes[1].set_ylabel('category')
plt.suptitle('Cluster 3')
fig, axes = plt.subplots(nrows=1, ncols=1)
df.loc[df[' cluster']==3,' description'].value_counts().plot(kind='bar', ax=axes)
axes.set_ylabel('description')
plt.suptitle('Cluster 3')
plt.show()
plt.close()